version: "3.3"

services:
  smarttimetable:
    container_name: smarttimetable
    restart: unless-stopped
    build:
      context: .
    volumes:
      # Mount data directory for CSV files
      - "./data:/code/data"
      # Mount logs directory for monitoring
      - "./logs:/code/logs"
    ports:
      - "9020:5000"
    environment:
            - COMPOSE_PROJECT_NAME=smarttimetable
    networks:
            - backend_welfare-board-strapi
networks:
  backend_welfare-board-strapi:
    external: true
