name: Deploy test Server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
      branches:
      - "dev"
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Establish ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
            cd /webapps/test-servers/smart-timetable
            git checkout dev
            git pull origin dev
            git status
            # Create logs directory if it doesn't exist
            mkdir -p logs
            # Stop existing containers
            docker-compose -f docker-compose.test.yml down
            # Build and start new containers
            docker-compose -f docker-compose.test.yml up -d --build
            # Show container status
            docker-compose -f docker-compose.test.yml ps
